spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Measuring-Tool
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: tool
#        format_sql: true
#        show_sql: true

  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  error:
    include-stacktrace: never

springdoc:
  api-docs:
#    enabled: false
    path: /tool-api-docs
  packages-to-scan: by.petrovich.tool.controller
  swagger-ui:
#    enabled: false
    path: /tool-documentation
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true

petrovich:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://tool-api.com


#appender: "com.p6spy.engine.spy.appender.FileLogger"
#logfile: "database.log"
#append: true
#logMessageFormat: "by.petrovich.tool.util.SpyCustomFormatter"
##customLogMessageFormat: "%(currentTime)|%(executionTime)|%(category)|%(sqlSingleLine)"
