spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Measuring-Tool
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: tool
        format_sql: true
        show_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  logging:
    level:
      root: INFO

server:
  error:
    include-stacktrace: never
